In [1]:
from ib_insync import *
util.startLoop()

ib = IB()
ib.connect('127.0.0.1', 7497, clientId=15)

In [2]:
# from ib_insync import *
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import math
import datetime 
import statsmodels.formula.api as smf 
from datetime import date, time, datetime, timedelta
import seaborn as sns
import random
from ta import add_all_ta_features
from ta.utils import dropna
from ta.trend import *

In [3]:
##### Initialization of global variables here ###

order_books = defaultdict(set)
df_ratio = pd.read_csv("ratio_dict.csv", index_col = 0).set_index("Pair")
df_global = pd.DataFrame({"date":[]})


country_info = {
    "Australia":{"Currency": "AUD", 
                "Exchange": "SMART",
                "Pairs": aus_adr_underlying_pairs},
    
    "Japan":{"Currency": "JPY", 
             "Exchange": "TSEJ",
             "Pairs": jpn_adr_underlying_pairs},
    
    "China":{"Currency": "HKD", 
         "Exchange": "SEHK",
         "Pairs": hk_adr_underlying_pairs},
    
}

NameError: name 'defaultdict' is not defined

In [13]:
adr_symbol = "CAJ"
adr_exchange = 'SMART'
adr_currency = "USD"

underlying_symbol = '7751'
underlying_exchange = 'TSEJ'
underlying_currency = 'JPY'
underlying_country = "Japan"

adr_contract = Contract(symbol = adr_symbol, secType = 'STK', exchange = adr_exchange, currency = adr_currency)
ib.qualifyContracts(adr_contract)
underlying_contract = Contract(symbol = underlying_symbol, secType = 'STK', exchange = underlying_exchange, currency = underlying_currency)
ib.qualifyContracts(underlying_contract)

history = '60 S'
freq = '1 min'
side ='Trades'

df_test = get_data(adr_contract, history, freq, side)

In [14]:
df_test

                 date   open   high    low  close  volume  average  barCount
0 2021-04-21 15:59:00  23.43  23.44  23.42  23.44      27   23.432        20

In [58]:
#define a function to get IB data. endDate is the last date of the historical data 

def get_data(contract, history, freq, side, endDate =''):
    bar = ib.reqHistoricalData(
        contract,
        endDateTime = endDate,
        durationStr=history,
        barSizeSetting= freq,
        whatToShow=side,
        useRTH=True,
        formatDate=1)
    return util.df(bar)

history = '300 S'
freq = '1 min'
side ='Trades'

# write getter functions?

In [43]:
# Initialization of hard coded data

aus_adr_underlying_pairs = [
    ["ATHE", "ATH"],["GENE", "GTG"],["IMMP", "IMM"],["IMRN","IMC"],["JHX", "JHX"],["KZIA", "KZA"],
    ["MESO","MSB"],["PLL", "PLL"],["WBK","WBC"]
]

hk_adr_underlying_pairs = [
    ["ACH", "2600"],["BGNE", "6160"],["CEA","670"],["HNP", "902"],["LFC", "2628"],["PTR", "857"],
    ["SHI", "338"],["SNP","386"],["ZNH", "1055"]
]

jpn_adr_underlying_pairs = [
    ["CAJ", "7751"],["HMC","7267"],["IX","8591"],["MFG","8411"],["MUFG","8306"],["NMR","8604"],
    ["SMFG","8316"],["SONY","6758"],["TAK", "4502"],["TM", "7203"]
]

country_info = {
    "Australia":{"Currency": "AUD", 
                "Exchange": "SMART",
                "Pairs": aus_adr_underlying_pairs},
    
    "Japan":{"Currency": "JPY", 
             "Exchange": "TSEJ",
             "Pairs": jpn_adr_underlying_pairs},
    
    "HK":{"Currency": "HKD", 
         "Exchange": "SEHK",
         "Pairs": hk_adr_underlying_pairs},
    
}

forex_pairs = [("AUD", "USD"),  ("USD", "HKD"), ("USD","JPY")]


# functions return the market opening time adjusted for DST

us_dst = {
        2021: (datetime(2021, 3, 14), datetime(2021, 11, 7)),
        2020: (datetime(2020, 3, 8),  datetime(2020, 11, 1)),
        2019: (datetime(2019, 3, 10), datetime(2019, 11, 3)),
        2018: (datetime(2018, 3, 11), datetime(2018, 11, 4)),
        2017: (datetime(2017, 3, 12), datetime(2017, 11, 5)),
        2016: (datetime(2016, 3, 13), datetime(2016, 11, 6)),
        2015: (datetime(2015, 3, 9),  datetime(2015, 11, 2)),
    } 

def next_market_open_day(date_now):
    '''
    Returns today if Mon - Thurs, returns next Mon if Fri thru Sun
    '''
    while date_now.weekday()>4:
        date_now += timedelta(days = 1)
    return date_now

def AUS_opening(date_now):
    date_now = next_market_open_day(date_now)
    us_start, us_end = us_dst[date_now.year]
    if us_start < date_now and date_now < us_end:
        return datetime.combine(date_now,time(10,0)) - timedelta(hours = 14)
    else:
        return datetime.combine(date_now, time(10,0)) - timedelta(hours = 15)

def AUS_closing(date_now):
    open_time = AUS_opening(date_now)
    return open_time + timedelta(hours = 6)

def HK_opening(date_now):
    date_now = next_market_open_day(date_now)
    start, end = us_dst[date_now.year]
    if start < date_now and date_now < end:
        return datetime.combine(date_now,time(9,30)) - timedelta(hours = 12)
    else:
        return datetime.combine(date_now, time(9,30)) - timedelta(hours = 13)
    
def HK_closing(date_now):
    open_time = HK_opening(date_now)
    return open_time + timedelta(hours = 6.5)
    
def JPN_opening(date_now):
    date_now = next_market_open_day(date_now)
    start, end = us_dst[date_now.year]
    if start < date_now and date_now < end:
        return datetime.combine(date_now,time(9,0)) - timedelta(hours = 13)
    else:
        return datetime.combine(date_now,time(9,0)) - timedelta(hours = 14)
    
def JPN_closing(date_now):
    open_time = JPN_opening(date_now)
    return open_time + timedelta(hours = 6)

def US_opening(date_now):
    return datetime.combine(next_market_open_day(date_now),time(9,30))

def US_closing(date_now):
    return datetime.combine(next_market_open_day(date_now),time(16,0))

In [183]:
country_info = {
    "Australia":{"Currency": "AUD", 
                "Exchange": "SMART",
                "Pairs": aus_adr_underlying_pairs},
    
    "Japan":{"Currency": "JPY", 
             "Exchange": "TSEJ",
             "Pairs": jpn_adr_underlying_pairs},
    
    "HK":{"Currency": "HKD", 
         "Exchange": "SEHK",
         "Pairs": hk_adr_underlying_pairs},
    
}


# Store all the historical adr/underlying open and close data

df_global = pd.DataFrame({"date":[]})

def pull_asian_close(days = 1):
    global df_global, country_info

    today = datetime.now().date()
    history = f"{days} D"
    freq = "1 Day"
    side = 'Trades'
    
    df_asian_close = pd.DataFrame({"date":[]})
    for key in country_info.keys():
        pairs = country_info[key]["Pairs"]
        exchange = country_info[key]["Exchange"]
        currency = country_info[key]["Currency"]
        
        for p in pairs:
            underlying = p[1]
            contract = Contract(symbol = underlying, secType = 'STK', exchange = exchange, currency = currency)
            try:
                df = get_data(contract, history, freq, side, endDate =today)
                df = df.loc[:, ["date", "close"]]
                col_name = "underlying_" + underlying + "_close"
                df = df.rename(columns = {"close":col_name})
#                 print(df)
                df_asian_close = pd.merge(df, df_asian_close, how = "outer")
            except:
                pass
            
    df_global = pd.concat([df_global, df_asian_close])

    
    
def pull_us_close(days = 1):
    global df_global, country_info

    today = datetime.now().date()
    history = f"{days} D"
    freq = "1 Day"
    side = 'Trades'
    
    df_us_close = pd.DataFrame({"date":[]})
    for key in country_info.keys():
        pairs = country_info[key]["Pairs"]
        exchange = "SMART"
        currency = "USD"
        
        for p in pairs:
            underlying = p[0] # get the ticker of the ADR
            contract = Contract(symbol = underlying, secType = 'STK', exchange = exchange, currency = currency)
            df = get_data(contract, history, freq, side, endDate ='')
            df = df.loc[:, ["date", "close"]]
            col_name = "adr_" + underlying + "_close"
            df = df.rename(columns = {"close":col_name})
            df_us_close = pd.merge(df, df_us_close, how = 'outer')
            
    df_global = pd.merge(df_global, df_us_close,how = 'outer')


def pull_forex_data(history = "1 D", freq = "1 min", side = "BID_ASK", end_date = "" ):
    '''
    Updates all three forex pairs
    '''
    
    global df_global, country_info, forex_pairs, test

    df_temp = pd.DataFrame({"date":[]})
    for currency1, currency2 in forex_pairs:
        contract = Contract(symbol = currency1, secType = 'CASH', exchange = "IDEALPRO", currency = currency2)
        df = get_data(contract, history, freq, side)

        if currency2 == "USD":
            df[f"{currency1}.{currency2}"] = (df["open"] + df["close"])/2
            forex_string = f"{currency1}.{currency2}"
        else:
            df[f"{currency2}.{currency1}"] = 2/(df["open"] + df["close"])
            forex_string = f"{currency2}.{currency1}"
        df_temp = pd.merge(df_temp, df[['date',forex_string]], how = "outer")
    
    df_forex = pd.merge(df_forex, df_temp, how = "outer")

In [ ]:
# def pull_forex_data(history = "1 D", freq = "1 min", side = "BID_ASK", end_date = "" ):
#     '''
#     Updates all three forex pairs
#     '''
    
#     global df_global, country_info, forex_pairs, test

    
#     df_forex = pd.DataFrame({"date":[]})
#     for currency1, currency2, asian_opening in forex_pairs:
#         contract = Contract(symbol = currency1, secType = 'CASH', exchange = "IDEALPRO", currency = currency2)
#         df = get_data(contract, history, freq, side)

#         if currency2 == "USD":
#             df["mid"] = (df["open"] + df["close"])/2
#             forex_string = f"{currency1}.{currency2}"
#         else:
#             df["mid"] = 2/(df["open"] + df["close"])
#             forex_string = f"{currency2}.{currency1}"

#         df = df.loc[:, ["date", "MID"]]
#         df_us_open = df[[(minute == US_opening(minute)) for minute in df["date"]]]

#         df_asian_open = df[[(minute == asian_opening(minute)) for minute in df["date"]]]


#         df_us_open = df_us_open.rename(columns = {"close":f"{forex_string}_MID_US_open"})
#         df_asian_open = df_asian_open.rename(columns = {"close":f"{forex_string}_MID_{currency2}_open"})

#         df_forex = pd.merge(df_forex, df_us_open, how = "outer")
#         df_forex = pd.merge(df_forex, df_asian_open, how = "outer")

#         df_global = pd.concat([df_global, df_forex])
#         df_global.to_csv("global_df.csv")

In [4]:
# pull_asian_close(10)
# pull_us_close(10)
# pull_forex_data()

Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1100, reqId -1: Connectivity between IB and Trader Workstation has been lost.
Error 1102, reqId -1: Connectivity between IB and Trader Workstation has been restored - data maintained. All data farms are connected: jfarm; cashhmds; hkhmds; ushmds; secdefil.

In [28]:

def z_score()

In [18]:
currency1 = "AUD"
secType = "CASH"
currency2 = "USD"
exchange = "IDEALPRO"

history = "1 D"
freq = "1 min"
side = "BID_ASK"

forex_contract = Contract(symbol = currency1, secType = secType, exchange = exchange, currency = currency2)
ib.qualifyContracts(forex_contract)
df_forex = get_data(forex_contract, history, freq, side)

In [ ]:
# 8.30 am
    # Pull Historical Forex Data (Minute, for lookback window)
    # Pull Close Data for Asian Market at 9am (Before US Market opens)
# 9.28 am 
    # Pull Forex Data for three currencies (For Z score)
    # Calculate Z Score 
    # for each pair:
        # if invested:
            # if risk condition or exit condition:
                # liquidate
            # else:
                # continue
        # if entry condition:
            # determine order size from risk metric and ADT over last 5 days
            # if 0: no order made
            # else: 
                # Define contract
                # make order (What order? Market Order?)


# 6 pm
    # Pull Close Data for US Market at 6pm (Before Asian Market opens)
    # Pull Historical Forex Data

# 2 min before Asian Market Open
    # Pull Forex Data
    # Calculate Z score using market close and minute forex data

In [182]:
# initialize data lists, hyperparameters etc

path_data = "live_trading_data/"
df_forex = pd.DataFrame({"date":[]})
def initialize_forex():
    global df_forex, country_info

    now = datetime.now()
    df_forex = pd.read_csv(f"{path_data}df_forex.csv")
    df_forex["date"] = [datetime.strptime(date_time, '%Y-%m-%d %H:%M:%S') for date_time in df_forex["date"]]
    pull_head = max(now-timedelta(days = round(7/5*100)),df_forex["date"].iloc[-1])


    now = datetime.now()
    df_temp_2 = pd.DataFrame({"date":[]})
    while pull_head < now:
        print(pull_head.date())
        for currency1, currency2 in forex_pairs:

            history = "1 D"
            freq = "1 min"
            side = "BID_ASK"

            forex_contract = Contract(symbol = currency1, secType = "CASH", exchange = "IDEALPRO", currency = currency2)
            ib.qualifyContracts(forex_contract)
            df_temp = get_data(forex_contract, history, freq, side)

            if currency2 == "USD":
                df_temp[f"{currency1}.{currency2}"] = (df_temp["open"] + df_temp["close"])/2
                forex_string = f"{currency1}.{currency2}"
            else:
                df_temp[f"{currency2}.{currency1}"] = 2/(df_temp["open"] + df_temp["close"])
                forex_string = f"{currency2}.{currency1}"

            df_temp["date"] = df_temp["date"].astype('datetime64[s]')
            df_temp_2 = pd.merge(df_temp_2, df_temp[["date",forex_string]], how = "outer")



        pull_head += timedelta(days = 1)
    df_forex = pd.merge(df_forex,df_temp_2, how = "outer")
    df_forex.to_csv(f"{path_data}df_forex.csv", index = False)
    print("df_forex initialized")

                      date   JPY.USD   AUD.USD   HKD.USD
978860 2021-04-22 02:33:00  0.009260  0.775145  0.128858
978861 2021-04-22 02:34:00  0.009261  0.775290  0.128858
978862 2021-04-22 02:35:00  0.009262  0.775360  0.128859
978863 2021-04-22 02:36:00  0.009262  0.775350  0.128859
978864 2021-04-22 02:37:00  0.009262  0.775375  0.128859
978865 2021-04-22 02:38:00  0.009262  0.775385  0.128861
978866 2021-04-22 02:39:00  0.009263  0.775470  0.128861
978867 2021-04-22 02:40:00  0.009264  0.775490  0.128860
978868 2021-04-22 02:41:00  0.009264  0.775465  0.128860
978869 2021-04-22 02:41:00       NaN       NaN  0.128860

In [166]:
df_forex = pd.read_csv(f"{path_data}df_forex.csv")
df_forex["date"] = [datetime.strptime(date_time, '%Y-%m-%d %H:%M:%S') for date_time in df_forex["date"]]

In [170]:
df_forex

                      date   JPY.USD   AUD.USD   HKD.USD
0      2020-11-30 17:15:00  0.009587  0.734580  0.129011
1      2020-11-30 17:16:00  0.009587  0.734490  0.129011
2      2020-11-30 17:17:00  0.009587  0.734445  0.129011
3      2020-11-30 17:18:00  0.009587  0.734460  0.129011
4      2020-11-30 17:19:00  0.009586  0.734565  0.129011
5      2020-11-30 17:20:00  0.009586  0.734610  0.129011
6      2020-11-30 17:21:00  0.009586  0.734630  0.129011
7      2020-11-30 17:22:00  0.009586  0.734635  0.129011
8      2020-11-30 17:23:00  0.009587  0.734695  0.129011
9      2020-11-30 17:24:00  0.009587  0.734695  0.129011
10     2020-11-30 17:25:00  0.009587  0.734765  0.129011
11     2020-11-30 17:26:00  0.009586  0.734875  0.129011
12     2020-11-30 17:27:00  0.009586  0.734875  0.129011
13     2020-11-30 17:28:00  0.009586  0.734860  0.129011
14     2020-11-30 17:29:00  0.009586  0.734840  0.129011
15     2020-11-30 17:30:00  0.009586  0.734850  0.129011
16     2020-11-30 17:31:00  0.009587  0.734855  0.129011
17     2020-11-30 17:32:00  0.009587  0.734880  0.129011
18     2020-11-30 17:33:00  0.009586  0.734850  0.129012
19     2020-11-30 17:34:00  0.009587  0.734770  0.129012
20     2020-11-30 17:35:00  0.009587  0.734770  0.129001
21     2020-11-30 17:36:00  0.009587  0.734760  0.129000
22     2020-11-30 17:37:00  0.009587  0.734740  0.129000
23     2020-11-30 17:38:00  0.009587  0.734750  0.129000
24     2020-11-30 17:39:00  0.009587  0.734740  0.129000
25     2020-11-30 17:40:00  0.009587  0.734685  0.129000
26     2020-11-30 17:41:00  0.009587  0.734740  0.129000
27     2020-11-30 17:42:00  0.009587  0.735005  0.129000
28     2020-11-30 17:43:00  0.009587  0.734960  0.129000
29     2020-11-30 17:44:00  0.009587  0.734940  0.129000
...                    ...       ...       ...       ...
978272 2021-04-19 16:30:00  0.009245  0.775570  0.128771
978273 2021-04-19 16:31:00  0.009245  0.775635  0.128771
978274 2021-04-19 16:32:00  0.009245  0.775705  0.128771
978275 2021-04-19 16:33:00  0.009245  0.775790  0.128771
978276 2021-04-19 16:34:00  0.009245  0.775785  0.128770
978277 2021-04-19 16:35:00  0.009245  0.775690  0.128770
978278 2021-04-19 16:36:00  0.009245  0.775685  0.128770
978279 2021-04-19 16:37:00  0.009245  0.775690  0.128771
978280 2021-04-19 16:38:00  0.009245  0.775700  0.128771
978281 2021-04-19 16:39:00  0.009246  0.775725  0.128771
978282 2021-04-19 16:40:00  0.009246  0.775790  0.128770
978283 2021-04-19 16:41:00  0.009246  0.775860  0.128771
978284 2021-04-19 16:42:00  0.009246  0.775915  0.128771
978285 2021-04-19 16:43:00  0.009246  0.775935  0.128770
978286 2021-04-19 16:44:00  0.009246  0.775925  0.128770
978287 2021-04-19 16:45:00  0.009246  0.775825  0.128765
978288 2021-04-19 16:46:00  0.009246  0.775780  0.128765
978289 2021-04-19 16:47:00  0.009247  0.775750  0.128763
978290 2021-04-19 16:48:00  0.009247  0.775780  0.128763
978291 2021-04-19 16:49:00  0.009247  0.775780  0.128762
978292 2021-04-19 16:50:00  0.009247  0.775815  0.128762
978293 2021-04-19 16:51:00  0.009247  0.775800  0.128762
978294 2021-04-19 16:52:00  0.009247  0.775790  0.128761
978295 2021-04-19 16:53:00  0.009247  0.775795  0.128763
978296 2021-04-19 16:54:00  0.009247  0.775750  0.128763
978297 2021-04-19 16:55:00  0.009247  0.775815  0.128764
978298 2021-04-19 16:56:00  0.009247  0.775850  0.128763
978299 2021-04-19 16:57:00  0.009248  0.775810  0.128761
978300 2021-04-19 16:58:00  0.009248  0.775775  0.128765
978301 2021-04-19 16:59:00  0.009247  0.775775  0.128764

[978302 rows x 4 columns]

In [169]:
pd.merge(df_forex, pd.merge(df_temp2[["date", "JPY.USD"]], df_temp[["date", "HKD.USD"]], how = "outer"), how = "outer")

                      date   JPY.USD   AUD.USD   HKD.USD
0      2020-11-30 17:15:00  0.009587  0.734580  0.129011
1      2020-11-30 17:16:00  0.009587  0.734490  0.129011
2      2020-11-30 17:17:00  0.009587  0.734445  0.129011
3      2020-11-30 17:18:00  0.009587  0.734460  0.129011
4      2020-11-30 17:19:00  0.009586  0.734565  0.129011
5      2020-11-30 17:20:00  0.009586  0.734610  0.129011
6      2020-11-30 17:21:00  0.009586  0.734630  0.129011
7      2020-11-30 17:22:00  0.009586  0.734635  0.129011
8      2020-11-30 17:23:00  0.009587  0.734695  0.129011
9      2020-11-30 17:24:00  0.009587  0.734695  0.129011
10     2020-11-30 17:25:00  0.009587  0.734765  0.129011
11     2020-11-30 17:26:00  0.009586  0.734875  0.129011
12     2020-11-30 17:27:00  0.009586  0.734875  0.129011
13     2020-11-30 17:28:00  0.009586  0.734860  0.129011
14     2020-11-30 17:29:00  0.009586  0.734840  0.129011
15     2020-11-30 17:30:00  0.009586  0.734850  0.129011
16     2020-11-30 17:31:00  0.009587  0.734855  0.129011
17     2020-11-30 17:32:00  0.009587  0.734880  0.129011
18     2020-11-30 17:33:00  0.009586  0.734850  0.129012
19     2020-11-30 17:34:00  0.009587  0.734770  0.129012
20     2020-11-30 17:35:00  0.009587  0.734770  0.129001
21     2020-11-30 17:36:00  0.009587  0.734760  0.129000
22     2020-11-30 17:37:00  0.009587  0.734740  0.129000
23     2020-11-30 17:38:00  0.009587  0.734750  0.129000
24     2020-11-30 17:39:00  0.009587  0.734740  0.129000
25     2020-11-30 17:40:00  0.009587  0.734685  0.129000
26     2020-11-30 17:41:00  0.009587  0.734740  0.129000
27     2020-11-30 17:42:00  0.009587  0.735005  0.129000
28     2020-11-30 17:43:00  0.009587  0.734960  0.129000
29     2020-11-30 17:44:00  0.009587  0.734940  0.129000
...                    ...       ...       ...       ...
978828 2021-04-22 02:01:00  0.009257       NaN  0.128855
978829 2021-04-22 02:02:00  0.009256       NaN  0.128848
978830 2021-04-22 02:03:00  0.009256       NaN  0.128847
978831 2021-04-22 02:04:00  0.009256       NaN  0.128848
978832 2021-04-22 02:05:00  0.009256       NaN  0.128848
978833 2021-04-22 02:06:00  0.009257       NaN  0.128849
978834 2021-04-22 02:07:00  0.009257       NaN  0.128847
978835 2021-04-22 02:08:00  0.009257       NaN  0.128846
978836 2021-04-22 02:09:00  0.009258       NaN  0.128846
978837 2021-04-22 02:10:00  0.009258       NaN  0.128846
978838 2021-04-22 02:11:00  0.009257       NaN  0.128846
978839 2021-04-22 02:12:00  0.009257       NaN  0.128846
978840 2021-04-22 02:13:00  0.009257       NaN  0.128844
978841 2021-04-22 02:14:00  0.009257       NaN  0.128844
978842 2021-04-22 02:15:00  0.009257       NaN  0.128845
978843 2021-04-22 02:16:00  0.009257       NaN  0.128848
978844 2021-04-22 02:17:00  0.009256       NaN  0.128848
978845 2021-04-22 02:18:00  0.009256       NaN  0.128849
978846 2021-04-22 02:19:00  0.009256       NaN  0.128849
978847 2021-04-22 02:20:00  0.009256       NaN  0.128849
978848 2021-04-22 02:21:00  0.009256       NaN  0.128849
978849 2021-04-22 02:22:00  0.009257       NaN  0.128849
978850 2021-04-22 02:23:00  0.009257       NaN  0.128851
978851 2021-04-22 02:24:00  0.009258       NaN  0.128855
978852 2021-04-22 02:25:00  0.009258       NaN  0.128853
978853 2021-04-22 02:26:00  0.009259       NaN  0.128853
978854 2021-04-22 02:27:00  0.009259       NaN  0.128852
978855 2021-04-22 02:28:00       NaN       NaN  0.128852
978856 2021-04-22 02:29:00       NaN       NaN  0.128852
978857 2021-04-22 02:30:00       NaN       NaN  0.128852

[978858 rows x 4 columns]

In [ ]:
country_info = {
    "Australia":{"Currency": "AUD", 
                "Exchange": "SMART",
                "Pairs": aus_adr_underlying_pairs},
    
    "Japan":{"Currency": "JPY", 
             "Exchange": "TSEJ",
             "Pairs": jpn_adr_underlying_pairs},
    
    "HK":{"Currency": "HKD", 
         "Exchange": "SEHK",
         "Pairs": hk_adr_underlying_pairs},
    
}


live_data = {}
def pull_live_data():
    global live_data, country_info, forex_pairs
    
    dict_forex = {}
    for country in forex_pairs:
        currency1, currency2, * = country

        history = "60 S"
        freq = "1 min"
        side = "BID_ASK"

        forex_contract = Contract(symbol = currency1, secType = "CASH", exchange = "IDEALPRO", currency = currency2)
        ib.qualifyContracts(forex_contract)
        df_temp = get_data(forex_contract, history, freq, side)
        
        latest_tick = df_temp.iloc[-1]
        if currency2 == "USD":
            live_data[f"{currency1}.{currency2}"] = (latest_tick["open"] + latest_tick["close"])/2

        else:
            live_data[f"{currency2}.{currency2}"] = 2/(latest_tick["open"] + latest_tick["close"])
            
    for country in country_info.keys():
        currency = country_info[country]["Currency"]
        exchange = country_info[country]["Exchange"]
        pairs_list = country_info[country]["Pairs"]
        
        side = "Trades"

        for ticker_ADR, ticker_underlying in pairs_list:
            contract = Contract(symbol = ticker_ADR, secType = "STK", exchange = "SMART", currency = currency)
            ib.qualifyContracts(contract)
            df_temp = get_data(contract, history, freq, side)
            latest_tick = df_temp.iloc[-1]
            live_data[ticker_ADR] = latest_tick['close'] # NEED TO MULTIPLY BY ADR RATIO
            
            
            contract = Contract(symbol = ticker_underlying, secType = "STK", exchange = exchange, currency = currency)
            ib.qualifyContracts(contract)
            df_temp = get_data(contract, history, freq, side)
            latest_tick = df_temp.iloc[-1]
            if country == "Australia":
                live_data[ticker_ADR] = latest_tick['close'] * live_data["AUD.USD"] # NEED TO MULTIPLY BY ADR RATIO
            elif country == "Japan":
                live_data[ticker_ADR] = latest_tick['close'] * live_data["JPY.USD"] # NEED TO MULTIPLY BY ADR RATIO
            elif country == "HK":
                live_data[ticker_ADR] = latest_tick['close'] * live_data["HKD.USD"] # NEED TO MULTIPLY BY ADR RATIO
        
    
    
def intraday_trader(HK, AUS, JPN, US):

In [ ]:
def z_score

In [ ]:
# update date
while True:
    # keep track of what day it is
    today = datetime.date() # ideally the algorithm starts at 8am in the morning
    
    # keep track of how many times we pull data for calibration
    bef_us_pull = False
    bef_us_zscore = False
    bef_asia_pull = False
    bef_jpn_zscore = False
    bef_aus_zscore = False
    bef_hk_zscore = False
    
    # Various Open and Close hours for various markets
    
    US_open = US_opening(today)
    US_close = US_closing(today)
    HK_open = HK_opening(today + 1)
    HK_close = HK_closing(today + 1)
    JPN_open = JPN_opening(today + 1)
    JPN_close = JPN_closing(today + 1)
    AUS_open = AUS_opening(today + 1)
    AUS_close = AUS_closing(today + 1)
    
    # Keep track if pair is open
    
    while now < US_close and now < HK_close and now < JPN_close and now < AUS_close:
        HK_trading = False
        AUS_trading = False
        US_trading = False
        JPN_trading = False
        
        # Before US Market Open pull historical data
        if not bef_us_pull and now > US_open - timedelta(hours = 1):
            bef_us_pull = True

            # Pull asian close for underlying stocks
            pull_asian_close()
        
        # Right before US Market Open for Z Score
        if not bef_us_zscore and now > US_open - timedelta(minutes = 4):
            bef_us_zscore = True
            pull_forex_data(df_forex, history = "21600 seconds")
            # Calculate Z score and make decision on trade and size
            
        if US_open < now and now < US_close:
            # Pull minute data to check whether to liquidate positions
            # Check pending limit orders
            US_trading = True
            
        
        # before asian markets open, pull us market close
        if not bef_asia_pull and now > US_close + timedelta(hours = 1):
            bef_asia_pull = True
            # pull us close
        
        # before Hong Kong market open, pull forex to calculate Z score
        if not bef_hk_zscore and now > HK_open - timedelta(minutes = 4):
            bef_hk_zscore = True
            pull_forex_data(df_forex, history = "21600 seconds")
            # calculate Z score and make decision on trade and size
        
        # check on Hong Kong Stocks
        if HK_open < now and now < HK_close:
            # Pull minute data to check whether to liquidate positions
            HK_trading = True
            # Check pending limit orders
        
        # before Japan market open, pull forex to calculate Z score
        if not bef_jpn_zscore and now > JPN_opening(today) - timedelta(minutes = 4):
            bef_JPN_zscore = True
            pull_forex_data(df_forex, history = "21600 seconds")
            # calculate Z score and make decision on trade and size
        
        # check on Japan stocks
        if JPN_open < now and now < JPN_close:
            # Pull minute data to check whether to liquidate positions
            JPN_trading = True
            # Check pending limit orders
            
        # before Australia market open, pull forex to calculate Z score            
        if not bef_aus_zscore and now > AUS_opening(today) - timedelta(minutes = 4):
            bef_aus_zscore = True
            pull_forex_data(df_forex, history = "21600 seconds")
        
        # check on Australian Stocks
        if AUS_open < now and now < AUS_close:
            # Pull minute data to check whether to liquidate positions
            AUS_trading = True
            # Check pending limit orders         
        

        ib.sleep(120) # Loop every two minutes
        now = datetime.now()

[Contract(secType='STK', conId=13905840, symbol='7751', exchange='TSEJ', primaryExchange='TSEJ', currency='JPY', localSymbol='7751.T', tradingClass='7751')]